### ISSUE TITLE
Readme initial login username and password

### ISSUE THREAD

**Issue by yuanyuan2100** [ramsayleung/blog#14]
Hi Ramsay,
The initial login username and password seems not working at the moment. May I ask where can I find the correct one? 
BTW, I guess the server port has been changed to 1337.
Thank you.

**Comment by yuanyuan2100** [comment]
Found it! Never mind.
Thank you.

**Comment by ramsayleung** [comment]
I am gonna close this issue, if you have any issue, you could reopen it :)
